schema_version = "1.0.0"

id = "Extension_Backup"
version = "1.0.0"
name = "Extension Backup Utility"
tagline = "Backup or restore extensions via JSON. "
maintainer = "g3215440591.gmail.com"
type = "add-on"
website = "https://github.com/3215440591/blender-extension-backup"
tags = ["Backup", "Extension"]

blender_version_min = "4.2.0"
license = ["SPDX:Apache-2.0"]

location = "View3D > Sidebar > Extension Backup"
[permissions]
files = "Reading and writing config files"

